remote_theme: BDHU/minimalist
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

url: https://giminkang.github.io
repository: GiminKang/GiminKang.github.io
# color-scheme: auto
color-scheme: light

title: Gimin Kang
description: "B.S. student<br> Industrial and System Engineering, KAIST"
logo: "./assets/DA Form.jpg"

search: true
search_full_content: true

sidebar:
  - name: CV
    icon: <i class="fas fa-fw fa-file"></i>
    link: "https://giminkang.github.io/assets/Resume.pdf"
  - name: Email
    icon: <i class="fas fa-fw fa-envelope-square"></i>
    link: "mailto:kgm4752@kaist.ac.kr"
  - name: GitHub
    icon: <i class="fab fa-fw fa-github"></i>
    link: "https://github.com/GiminKang"
